version: "2"
services:
  songs_path_db:
    container_name: songs_path_db
    image: mongo
    ports:
      - "27017:27017"
  songs_path_ms:
    container_name: songs_path_ms
    restart: always
    build: .
    ports:
      - "3003:3003"
    links:
      - songs_path_db
  